### ISSUE TITLE
getMatchMapStats, TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by kelby** [gigobyte/HLTV#257]
getMatchMapStats({id: 98524})

ERROR

```
(node:93247) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /Users/Someone/node/spider-hltv/node_modules/hltv/lib/endpoints/getMatchMapStats.js:95:25
    at step (/Users/Someone/node/spider-hltv/node_modules/hltv/lib/endpoints/getMatchMapStats.js:44:23)
    at Object.next (/Users/Someone/node/spider-hltv/node_modules/hltv/lib/endpoints/getMatchMapStats.js:25:53)
    at fulfilled (/Users/Someone/node/spider-hltv/node_modules/hltv/lib/endpoints/getMatchMapStats.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:93247) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:93247) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Page: https://www.hltv.org/stats/matches/mapstatsid/98524/espada-vs-pro100

**Comment by gigobyte** [comment]
Are you sure you weren't rate-limited by HLTV? Your example works on my machine:
```
{
  matchPageID: 2339301,
  map: 'trn',
  date: 1581339300000,
  team1: { id: 7898, name: 'pro100', score: 25 },
  team2: { id: 8669, name: 'Espada', score: 22 },
  event: { id: 5214, name: 'WESG 2019 Russia Closed Qualifier' },
  overview: {
    rating: { team1: 1.17, team2: 0.92 },
    firstKills: { team1: 25, team2: 22 },
    clutchesWon: { team1: 1, team2: 6 },
    mostKills: { id: 19673, name: 'Patsi', value: 43 },
    mostDamage: { id: 13915, name: 'YEKINDAR', value: 100 },     
    mostAssists: { id: 11498, name: 'NickelBack', value: 10 },   
    mostAWPKills: { id: 7403, name: 'WorldEdit', value: 31 },
    mostFirstKills: { id: 13915, name: 'YEKINDAR', value: 8 },
    bestRating: { id: 13915, name: 'YEKINDAR', value: 1.33 }
  },
  roundHistory: [
    { outcome: 'ct_win', score: '0-1', ctTeam: 8669, tTeam: 7898 },
    { outcome: 'ct_win', score: '0-2', ctTeam: 8669, tTeam: 7898 },
    {
      outcome: 'bomb_defused',
      score: '0-3',
      ctTeam: 8669,
      tTeam: 7898
    },
    {
      outcome: 'bomb_defused',
      score: '0-4',
      ctTeam: 8669,
      tTeam: 7898
    },
    {
      outcome: 'bomb_exploded',
      score: '1-4',
      ctTeam: 8669,
      tTeam: 7898
    },
    { outcome: 't_win', score: '2-4', ctTeam: 8669, tTeam: 7898 },
    { outcome: 'ct_win', score: '2-5', ctTeam: 8669, tTeam: 7898 },
    { outcome: 't_win', score: '3-5', ctTeam: 8669, tTeam: 7898 },
    { outcome: 'ct_win', score: '3-6', ctTeam: 8669, tTeam: 7898 },
    { outcome: 'ct_win', score: '3-7', ctTeam: 8669, tTeam: 7898 },
    {
      outcome: 'bomb_exploded',
      score: '4-7',
      ctTeam: 8669,
      tTeam: 7898
    },
    { outcome: 'ct_win', score: '4-8', ctTeam: 8669, tTeam: 7898 },
    { outcome: 't_win', score: '5-8', ctTeam: 8669, tTeam: 7898 },
    { outcome: 't_win', score: '6-8', ctTeam: 8669, tTeam: 7898 },
    { outcome: 'ct_win', score: '6-9', ctTeam: 8669, tTeam: 7898 },
    { outcome: 't_win', score: '6-10', ctTeam: 7898, tTeam: 8669 },
    { outcome: 'ct_win', score: '7-10', ctTeam: 7898, tTeam: 8669 },
    { outcome: 'ct_win', score: '8-10', ctTeam: 7898, tTeam: 8669 },
    { outcome: 'ct_win', score: '9-10', ctTeam: 7898, tTeam: 8669 },
    {
      outcome: 'bomb_exploded',
      score: '9-11',
      ctTeam: 7898,
      tTeam: 8669
    },
    { outcome: 't_win', score: '9-12', ctTeam: 7898, tTeam: 8669 },
    { outcome: 'ct_win', score: '10-12', ctTeam: 7898, tTeam: 8669 },
    {
      outcome: 'bomb_defused',
      score: '11-12',
      ctTeam: 7898,
      tTeam: 8669
    },
    { outcome: 'ct_win', score: '12-12', ctTeam: 7898, tTeam: 8669 },
    { outcome: 'ct_win', score: '13-12', ctTeam: 7898, tTeam: 8669 },
    { outcome: 'ct_win', score: '14-12', ctTeam: 7898, tTeam: 8669 },
    { outcome: 't_win', score: '14-13', ctTeam: 7898, tTeam: 8669 },
    { outcome: 'ct_win', score: '15-13', ctTeam: 7898, tTeam: 8669 },
    { outcome: 't_win', score: '15-14', ctTeam: 7898, tTeam: 8669 },
    { outcome: 't_win', score: '15-15', ctTeam: 7898, tTeam: 8669 }
  ],
  playerStats: {
    team1: [
      {
        id: 13915,
        name: 'YEKINDAR',
        kills: 40,
        hsKills: 22,
        assists: 8,
        flashAssists: 0,
        deaths: 29,
        KAST: 63.8,
        killDeathsDifference: 11,
        ADR: 100,
        firstKillsDifference: -2,
        rating: 1.33,
        killsPerRound: 0.85,
        deathsPerRound: 0.62,
        impact: 1.64
      },
      {
        id: 7796,
        name: 'wayLander',
        kills: 39,
        hsKills: 17,
        assists: 9,
        flashAssists: 0,
        deaths: 33,
        KAST: 76.6,
        killDeathsDifference: 6,
        ADR: 86,
        firstKillsDifference: -3,
        rating: 1.21,
        killsPerRound: 0.83,
        deathsPerRound: 0.7,
        impact: 1.13
      },
      {
        id: 7403,
        name: 'WorldEdit',
        kills: 36,
        hsKills: 6,
        assists: 6,
        flashAssists: 2,
        deaths: 25,
        KAST: 80.9,
        killDeathsDifference: 11,
        ADR: 62.9,
        firstKillsDifference: 1,
        rating: 1.18,
        killsPerRound: 0.77,
        deathsPerRound: 0.53,
        impact: 1.05
      },
      {
        id: 11498,
        name: 'NickelBack',
        kills: 33,
        hsKills: 14,
        assists: 17,
        flashAssists: 7,
        deaths: 32,
        KAST: 80.9,
        killDeathsDifference: 1,
        ADR: 87.6,
        firstKillsDifference: 4,
        rating: 1.16,
        killsPerRound: 0.7,
        deathsPerRound: 0.68,
        impact: 0.94
      },
      {
        id: 13780,
        name: 'dimasick',
        kills: 29,
        hsKills: 15,
        assists: 8,
        flashAssists: 2,
        deaths: 31,
        KAST: 72.3,
        killDeathsDifference: -2,
        ADR: 62.6,
        firstKillsDifference: 3,
        rating: 0.94,
        killsPerRound: 0.62,
        deathsPerRound: 0.66,
        impact: 0.77
      }
    ],
    team2: [
      {
        id: 19673,
        name: 'Patsi',
        kills: 43,
        hsKills: 26,
        assists: 5,
        flashAssists: 3,
        deaths: 35,
        KAST: 72.3,
        killDeathsDifference: 8,
        ADR: 92.7,
        firstKillsDifference: -2,
        rating: 1.23,
        killsPerRound: 0.91,
        deathsPerRound: 0.74,
        impact: 1.25
      },
      {
        id: 17306,
        name: 'degster',
        kills: 32,
        hsKills: 9,
        assists: 4,
        flashAssists: 1,
        deaths: 33,
        KAST: 61.7,
        killDeathsDifference: -1,
        ADR: 70.8,
        firstKillsDifference: 2,
        rating: 0.99,
        killsPerRound: 0.68,
        deathsPerRound: 0.7,
        impact: 1.12
      },
      {
        id: 9081,
        name: 'S0tF1k',
        kills: 27,
        hsKills: 11,
        assists: 6,
        flashAssists: 1,
        deaths: 34,
        KAST: 63.8,
        killDeathsDifference: -7,
        ADR: 73.3,
        firstKillsDifference: 2,
        rating: 0.91,
        killsPerRound: 0.57,
        deathsPerRound: 0.72,
        impact: 0.87
      },
      {
        id: 8125,
        name: 'Dima',
        kills: 28,
        hsKills: 20,
        assists: 7,
        flashAssists: 1,
        deaths: 37,
        KAST: 59.6,
        killDeathsDifference: -9,
        ADR: 71.9,
        firstKillsDifference: -4,
        rating: 0.86,
        killsPerRound: 0.6,
        deathsPerRound: 0.79,
        impact: 0.92
      },
      {
        id: 17305,
        name: 'FinigaN',
        kills: 20,
        hsKills: 9,
        assists: 5,
        flashAssists: 1,
        deaths: 38,
        KAST: 55.3,
        killDeathsDifference: -18,
        ADR: 49.8,
        firstKillsDifference: -1,
        rating: 0.6,
        killsPerRound: 0.43,
        deathsPerRound: 0.81,
        impact: 0.5
      }
    ]
  },
  performanceOverview: {
    team1: { kills: 177, deaths: 150, assists: 37 },
    team2: { kills: 150, deaths: 177, assists: 20 }
  }
}
Done in 5.89s.
```
