### ISSUE TITLE
getMatch is returning an error

### ISSUE THREAD

**Issue by Felipevieira2** [gigobyte/HLTV#324]
my code: 
async function getMatch() {
    let teste = await HLTV.getMatch({id: 2343190}).then((res) => {
        
        return res;
    }).catch( error => { 
        console.log(error);
    })
    
    console.log(teste);    
}

ID Match: 2343190

TypeError: Cannot read property 'split' of undefined
    at C:\Users\User\Documents\dev\hltv\node_modules\hltv\lib\endpoints\getMatch.js:96:93
    at step (C:\Users\User\Documents\dev\hltv\node_modules\hltv\lib\endpoints\getMatch.js:33:23)
    at Object.next (C:\Users\User\Documents\dev\hltv\node_modules\hltv\lib\endpoints\getMatch.js:14:53)
    at fulfilled (C:\Users\User\Documents\dev\hltv\node_modules\hltv\lib\endpoints\getMatch.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by gigobyte** [comment]
Cloudflare is blocking you.
