### ISSUE TITLE
getResults return "featured results" even if they are not between the start and the end date

### ISSUE THREAD

**Issue by LovelyPinguin** [gigobyte/HLTV#446]
When executing this line
`const matches = await HLTV.getResults({ startDate: '2021-04-04' , endDate: '2021-04-04' , delayBetweenPageRequests: 300 })`
i get this result :

[result.txt](https://github.com/gigobyte/HLTV/files/6254887/result.txt)

the code here gather the 3 featured matches first with an undefined date and, if the match was not played  between the start and the end date specified, the id is undefinded and throw an error message

`TypeError: Cannot read property 'split' of undefined
    at getIdAt (C:\Users\Yvan\Desktop\NickName\node_modules\hltv\lib\utils.js:93:45)
    at C:\Users\Yvan\Desktop\NickName\node_modules\hltv\lib\utils.js:91:45
    at Object.attrThen (C:\Users\Yvan\Desktop\NickName\node_modules\hltv\lib\scraper.js:35:20)
    at C:\Users\Yvan\Desktop\NickName\node_modules\hltv\lib\endpoints\getResults.js:93:52
    at Array.map (<anonymous>)
    at step (C:\Users\Yvan\Desktop\NickName\node_modules\hltv\lib\endpoints\getResults.js:44:23)
    at Object.next (C:\Users\Yvan\Desktop\NickName\node_modules\hltv\lib\endpoints\getResults.js:25:53)
    at fulfilled (C:\Users\Yvan\Desktop\NickName\node_modules\hltv\lib\endpoints\getResults.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by gigobyte** [comment]
Ah I missed that, will fix soon.
