### ISSUE TITLE
fix for error on empty mapstatistics

### ISSUE THREAD

**Issue by marcobuettner** [gigobyte/HLTV#70]
Sometimes I got this error

```
(node:7959) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at Object.exports.getMapsStatistics (/home/discord/scorebottest/node_modules/hltv/lib/utils/mappers.js:118:17)
    at Object.<anonymous> (/home/discord/scorebottest/node_modules/hltv/lib/endpoints/getTeam.js:96:47)
    at step (/home/discord/scorebottest/node_modules/hltv/lib/endpoints/getTeam.js:32:23)
    at Object.next (/home/discord/scorebottest/node_modules/hltv/lib/endpoints/getTeam.js:13:53)
    at fulfilled (/home/discord/scorebottest/node_modules/hltv/lib/endpoints/getTeam.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:7959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7959) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have found a way to fix this

change line 96 from

```javascript
mapStatistics = mappers_1.getMapsStatistics(t$(t$('.graph').get(1)).attr('data-fusionchart-config'));
```

into this

```javascript
try {
    mapStatistics = mappers_1.getMapsStatistics(t$(t$('.graph').get(1)).attr('data-fusionchart-config'));
} catch(_c) {
    mapStatistics = [];
}
```
The error appears when I try to get details from team "tempo storm" (HLTV teamId: 6118) from HLTV

**Comment by gigobyte** [comment]
Fixed in version `2.8.2`
