### ISSUE TITLE
Maybe some changes on HLTV?

### ISSUE THREAD

**Issue by marcobuettner** [gigobyte/HLTV#74]
Since today I got this messages. I try to fetch details from this game https://www.hltv.org/matches/2326680/w7m-vs-furia-inagame-aorus-league-2018-season-3-brazil

**getMatch.js**

```
(node:16311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16311) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:16311) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at /home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getMatch.js:120:97
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getMatch.js:112:87)
    at step (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getMatch.js:32:23)
    at Object.next (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getMatch.js:13:53)
    at fulfilled (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getMatch.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:16311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**getTeam.js**

```
(node:30319) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:30319) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at getPlayerId (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getTeam.js:65:48)
    at /home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getTeam.js:68:29
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getTeam.js:66:122)
    at step (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getTeam.js:32:23)
    at Object.next (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getTeam.js:13:53)
    at fulfilled (/home/scidev2/Bots/hltv-scorebot/node_modules/hltv/lib/endpoints/getTeam.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:30319) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

**Comment by clappis** [comment]
I got the same error.. i fix as contingency:

parsing.js on line 6
exports.popSlashSource = function (el) { return el.attr('src') ? el.attr('src').split('/').pop() : el.attr('data-cfsrc').split('/').pop(); };

getMatch.js on line 120
Number(matchEl.find('.winner .flag').next().next().attr('href').split('/')[2])

**Comment by gigobyte** [comment]
I think that the error was only present while the match was running, because now it works fine when I test it.

**Comment by clappis** [comment]
> I think that the error was only present while the match was running, because now it works fine when I test it.

can be, but my script only looks for matches that already appear on the results screen, idk if on results page appear matchs running, I'll test later, thanks for u answer
