### ISSUE TITLE
TypeError: HLTV.getMatch is not a function

### ISSUE THREAD

**Issue by lucascorrea** [gigobyte/HLTV#888]
Hey guys, 

I'm trying to use the HLTV 3.5.0 version. However, I got an error.

Could someone help me to integrate the lib? Thank you.

server.js
```javascript
import HLTV from 'hltv'

async function fetchMatchData(matchId) {
    try {
        const match = await HLTV.getMatch({ id: matchId })
        console.log(match)
    } catch (error) {
        console.error('Error:', error)
    }
}

fetchMatchData(2306295)
``` 

package.json
```javascript 
{
  "name": "cslivestats",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "hltv": "^3.5.0"
  }
}
```

Error
```
$ node src/server.js
Error: TypeError: HLTV.getMatch is not a function
    at fetchMatchData (file:///Users/lucascorrea/Projects/cslivestats/src/server.js:5:34)
    at file:///Users/lucascorrea/Projects/cslivestats/src/server.js:12:1
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

**Comment by gigobyte** [comment]
This library doesn't support ESM, it's CommonJS only.

**Comment by lucascorrea** [comment]
> This library doesn't support ESM, it's CommonJS only.

I will try it thank you

**Comment by lucascorrea** [comment]
> This library doesn't support ESM, it's CommonJS only.

It's working now. 
Thank you again.

Taking advantage of this, there is a function to obtain data from a live game, such as the game scoreboard to see the score.

**Comment by lucascorrea** [comment]
I've tried this function, however, it got stuck I didn't receive any update.

```
const { HLTV } = require('hltv')

HLTV.connectToScorebot({
    id: 2377346,
    onScoreboardUpdate: (data, done) => {
      // if you call done() the socket connection will close.
      console.log(data)
    },
    onLogUpdate: (data, done) => {
      console.log(data)
    }
  })
  ```

**Comment by MonsieurBibo** [comment]
@gigobyte does that mean you are searching for a maintainer ? In any case, I suggest you put it (=not maintained) on the README to inform users.

**Comment by gigobyte** [comment]
Done.
